set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "KonteX Neuroscience")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROJECT_NAME}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ThorVision Desktop Video Capture GUI App")

set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")

if(WIN32)
    include(InstallRequiredSystemLibraries)
    
    set(CPACK_GENERATOR "INNOSETUP")
    set(CPACK_INNOSETUP_USE_MODERN_WIZARD ON)
    set(CPACK_INNOSETUP_ICON_FILE "${CMAKE_SOURCE_DIR}/resources/xdaq-icon.ico")
    set(CPACK_INNOSETUP_CREATE_UNINSTALL_LINK ON)
    list(APPEND CPACK_INNOSETUP_EXTRA_SCRIPTS 
        "${CMAKE_SOURCE_DIR}/cmake/setup.iss"
    )
    
elseif(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_PRE_BUILD_SCRIPTS "${CMAKE_SOURCE_DIR}/cmake/codesign.cmake")
endif()

include(CPack)